Repository qhqo0403/sonane-book, pull requests merged in 2023-06, with the labels that each got.

#10 [Fix] #9 Fix Code Error
  project/src/App.js
Labels: Status: Reviewing, Type: Bugfix/Function

#15 [Feat] #14 Create My Page and Account Page
  project/src/App.js
  project/src/components/AccountForm.js
  project/src/components/MyTabMenu.js
  project/src/components/MyTabMenu.module.css
  project/src/index.js
  project/src/pages/Account.js
  project/src/pages/Authentication.js
  project/src/pages/Challenge.js
  project/src/pages/Error.js
  project/src/pages/FindPw.js
  project/src/pages/Home.js
  project/src/pages/Memo.js
  project/src/pages/My.js
  project/src/pages/MyChallenge.js
  project/src/pages/MyChallengeDetail.js
  project/src/pages/MyChallengeRoot.js
  project/src/pages/NewChallenge.js
  project/src/pages/NewReview.js
  project/src/pages/RecentReads.js
  project/src/pages/Review.js
  project/src/pages/Search.js
  project/src/pages/SearchResult.js
  project/src/pages/ToBeReads.js
Labels: Type: Feature/Function, Status: In Progress

#17 [Feat] #11 Add Header
  project/src/App.js
  project/src/components/MainNavigation.js
  project/src/components/Root.css
  project/src/pages/Authentication.js
  project/src/pages/Challenge.js
  project/src/pages/Error.js
  project/src/pages/FindPw.js
  project/src/pages/Memo.js
  project/src/pages/MyChallenge.js
  project/src/pages/MyChallengeDetail.js
  project/src/pages/MyChallengeRoot.js
  project/src/pages/NewChallenge.js
  project/src/pages/NewReview.js
  project/src/pages/RecentReads.js
  project/src/pages/Review.js
  project/src/pages/Root.js
  project/src/pages/Search.js
  project/src/pages/SearchResult.js
  project/src/pages/ToBeReads.js
Labels: Type: Feature/Function

#19 [Feat] #12 Add Footer
  project/src/components/Footer.js
  project/src/components/Header.js
  project/src/components/Root.css
  project/src/pages/Home.js
  project/src/pages/Root.js
Labels: Type: Feature/Function

#20 [Feat] #18 Tailwind CSS settings
  project/src/components/Footer.js
  project/src/components/Header.js
  project/src/components/Root.css
  project/src/index.css
  project/src/index.js
  project/tailwind.config.js
Labels: Type: Feature/Function

#21 [Feat] #13 Create Landing Component & HomeContent Component
  project/src/components/HomeContent.js
  project/src/components/Landing.js
  project/src/components/Root.css
  project/src/pages/Home.js
Labels: Type: Feature/Function

#23 [Remove] #22 Remove Root.css
  project/src/components/Root.css
  project/src/pages/Home.js
Labels: Type: Bugfix/Function

#25 [Feat] #16 Create and Connect My Challenge
  project/src/components/MyChallengeItem.js
  project/src/components/MyChallengeItem.module.css
  project/src/components/MyChallengeList.js
  project/src/components/MyChallengeList.module.css
  project/src/components/NewChallengeForm.js
  project/src/pages/MyChallenge.js
  project/src/pages/MyChallengeDetail.js
  project/src/pages/MyChallengeRoot.js
  project/src/pages/NewChallenge.js
Labels: Type: Feature/Function

#28 [Feat] #26 Create ToBeReads page
  project/src/components/BookList.js
  project/src/components/BookList.module.css
  project/src/components/ToBeReadBooks.js
  project/src/pages/ToBeReads.js
Labels: Type: Feature/Function, Status: In Progress

#29 [Feat] #27 Create RecentReads page
  project/src/components/RecentReadBooks.js
  project/src/pages/RecentReads.js
  project/src/pages/ToBeReads.js
Labels: Type: Feature/Function, Status: In Progress

#32 [Feat] #30 Create Review Page
  project/src/components/NewReviewForm.js
  project/src/components/ReviewDetailModal.js
  project/src/components/ReviewDetailModal.module.css
  project/src/components/ReviewItem.js
  project/src/components/ReviewItem.module.css
  project/src/components/ReviewList.js
  project/src/components/ReviewList.module.css
  project/src/pages/NewReview.js
  project/src/pages/Review.js
Labels: Type: Feature/Function, Status: Reviewing

#33 [Feat] #31 Create Memo Page
  project/src/components/MemoItem.js
  project/src/components/MemoItem.module.css
  project/src/components/MemoList.js
  project/src/components/MemoList.module.css
  project/src/components/NewMemoFormModal.js
  project/src/components/NewMemoFormModal.module.css
  project/src/pages/Memo.js
Labels: Type: Feature/Function, Status: In Progress
